#
# This file has been generated by Cycloid, please DO NOT modify.
# Any manual modifications done to this file, WILL be lost on the
# next project edition via the forms.
#
# Please note that comments in sample files will have been dropped
# due to some limitations upon files' generation.
#
# Any extra variables not found in the original file have been ignored.
#

module "onprem" {
  source = "./module-onprem"

  base_ami_id      = ""
  bastion_sg_allow = "${data.terraform_remote_state.infrastructure.outputs.test_bastion_sg_allow}"
  customer         = var.customer
  cy_instances_cidr_blocks_allow = [
    "0.0.0.0/0"
  ]
  cy_instances_count         = "1"
  cy_instances_disk_size     = 50
  cy_instances_ebs_optimized = false
  cy_instances_type          = "t3.small"
  debian_ami_name            = "debian-10-amd64-*"
  env                        = var.env
  extra_tags = {
    monitoring_discovery = "false"
  }
  keypair_name       = "cycloid"
  project            = var.project
  public_subnets_ids = "${data.terraform_remote_state.infrastructure.outputs.test_public_subnets_ids}"
  shared2_array = [
    "${a}",
    "${b}",
    "${c}"
  ]
  shared2_bool    = true
  shared2_string  = "eu-west-1"
  shared3_integer = 42
  shared3_map = {
    fi = "foo"
  }
  shared3_string = "bar"
  vpc_id         = "${data.terraform_remote_state.infrastructure.outputs.test_vpc_id}"
}

