first-usecase:
  pipeline:
    Radios:
    - widget: "radios"
      required: true
      values: [1, 2, 3]
      default: 3
      type: "integer"
      description: "key: radios_integer_required"
      key: "radios_integer_required"
      name: "Required radio (integer)"

    - widget: "radios"
      required: false
      values: [1, 2, 3]
      default: 3
      type: "integer"
      description: "key: radios_integer_required"
      key: "radios_integer_required"
      name: "Not required radio (integer)"

    - widget: "radios"
      required: true
      values: [[1, 2, 3], [4, 5, 6], ["a", "b", "c"]]
      type: "array"
      description: "key: radios_array"
      key: "radios_array"
      name: "Radios (Array)"
    - widget: "radios"
      required: true
      values: [{ myvar: 'key' }, { myvar2: true }, { myvar3: 3 }]
      type: "map"
      description: "key: radios_map"
      key: "radios_map"
      name: "Radios (Map)"

    - widget: "radios"
      required: true
      values: [[1, 2, 3], [4, 5, 6], ["a", "b", "c"]]
      default: [4, 5, 6]
      type: "array"
      description: "key: radios_array_default"
      key: "radios_array_default"
      name: "Radios (Array) with default"
    - widget: "radios"
      required: true
      values: [{ myvar: 'key' }, { myvar2: true }, { myvar3: 3 }]
      default: { myvar3: 3 }
      type: "map"
      description: "key: radios_map_default"
      key: "radios_map_default"
      name: "Radios (Map) with default"