version: "2"
name: Dan Stack
canonical: dan_stack
author: Daniele Gazzelloni
status: private
description: test stack
image: ""
keywords:
- test
- provider:aws
- provider:vault
technologies:
- technology: stackcraft
  version: "1"
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        path: default/pipeline/variables.sample.yaml
