version: "2"
name: test stack
canonical: test_stack
author: Daniele Gazzelloni
status: private
description: test
image: ""
keywords:
- test
- provider:aws
- provider:vault
technologies:
- technology: stackcraft
  version: "1"
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      test_stack:
        destination: ($ project $)/default/terraform/($ environment $)/test_stack.tf
        path: default/terraform/test_stack.tf.sample
