version: "2"
name: test-stack-should-not-work
canonical: test-stack-should-not-work
author: Daniele Gazzelloni
status: private
description: "11"
image: ""
keywords:
- test
- provider:flexibleengine
- provider:vault
technologies:
- technology: stackcraft
  version: "1"
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        path: default/pipeline/variables.sample.yaml
    terraform:
      test-stack-should-not-work:
        destination: ($ project $)/default/terraform/($ environment $)/test-stack-should-not-work.tf
        path: default/terraform/test-stack-should-not-work.tf.sample
