version: "2"
name: data-guyana-648
canonical: data-guyana-648
author: Daniele Gazzelloni
status: private
description: Officiis blanditiis labore ut. Et dolore nihil ipsam occaecati ipsam
  fugit fugit est. A tempore delectus.
image: ""
keywords:
- Checking
- provider:flexibleengine
- provider:vault
technologies:
- technology: stackcraft
  version: "1"
dependencies:
- ref: seraf:infra-amazon-s3
  required: true
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
