version: "2"
name: plications-intangible-566
canonical: plications-intangible-566
author: Daniele Gazzelloni
status: private
description: Iste et consequuntur sit nihil molestias omnis laborum magnam. Et ut
  quisquam nisi quasi doloribus non dolor non quisquam. Nobis recusandae et aut laborum
  quae commodi asperiores necessitatibus omnis. Eius molestiae distinctio ut commodi
  enim mollitia dolores. Et alias rerum est harum quis.
image: ""
keywords:
- Refined
- Bahamas
- provider:aws
- provider:vault
technologies:
- technology: stackcraft
  version: "1"
dependencies:
- ref: seraf:infra-amazon-s3
  required: true
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      plications-intangible-566:
        destination: ($ project $)/default/terraform/($ environment $)/plications-intangible-566.tf
        path: default/terraform/plications-intangible-566.tf.sample
