version: "2"
name: eyeballs-gorgeous-192
canonical: eyeballs-gorgeous-192
author: Daniele Gazzelloni
status: private
description: Dolorem est eum. Neque nihil explicabo consectetur dolorem culpa aut
  quo qui. Repellendus laborum est magni pariatur. Et dolore dolorem quibusdam. Qui
  voluptatum qui nesciunt.
image: ""
keywords:
- vortals
- SMTP
- provider:flexibleengine
- provider:vault
technologies:
- technology: stackcraft
  version: "1"
dependencies:
- ref: seraf:infra-amazon-s3
  required: true
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      eyeballs-gorgeous-192:
        destination: ($ project $)/default/terraform/($ environment $)/eyeballs-gorgeous-192.tf
        path: default/terraform/eyeballs-gorgeous-192.tf.sample
