#
# This file has been generated by Cycloid, please DO NOT modify.
# Any manual modifications done to this file, WILL be lost on the
# next project edition via the forms.
#
# Please note that comments in sample files will have been dropped
# due to some limitations upon files' generation.
#
# Any extra variables not found in the original file have been ignored.
#

module "vm" {
  source = "./module-ec2"

  ami_architecture                     = "x86_64"
  ami_most_recent                      = true
  ami_name                             = "debian-stretch-*"
  ami_owners                           = "379101102735"
  ami_root_device_type                 = "ebs"
  ami_virtualisation_type              = "hvm"
  associate_public_ip_address          = true
  customer                             = var.customer
  ebs_optimized                        = false
  enable_vm_disk_delete_on_termination = true
  enable_vm_disk_encrypted             = true
  env                                  = var.env
  file_content                         = ""
  instance_extra_tags                  = {}
  instance_type                        = "t2.large"
  private_ip                           = ""
  project                              = var.project
  sg_egress_rules = [
    {
      description      = "Accept all egress"
      from_port        = 0
      to_port          = 0
      protocol         = "-1"
      cidr_blocks      = ["0.0.0.0/0"]
      ipv6_cidr_blocks = []
      prefix_list_ids  = []
      security_groups  = []
      self             = true
    }
  ]

  sg_extra_tags = {}
  sg_ingress_rules = [
    {
      description      = "Accept ssh traffic"
      from_port        = 22
      to_port          = 22
      protocol         = "tcp"
      cidr_blocks      = ["0.0.0.0/0"]
      ipv6_cidr_blocks = []
      prefix_list_ids  = []
      security_groups  = []
      self             = true
    }
  ]

  sg_name           = ""
  subnet_id         = "ok"
  vm_disk_size      = 5
  vm_disk_type      = "gp2"
  volume_extra_tags = {}
  vpc_id            = "test"
}

