# Configuration of the CI pipeline
version: '2'
name: 'Magento (forms)'
canonical: 'stack-magento-v2-forms'
description: 'A stack with 1 pipeline. Packed with forms content.'
keywords:
  - 'stack'
  - 'public'
author: 'dangz0'
image: 'https://d29fhpw069ctt2.cloudfront.net/icon/image/38645/preview.svg'
type: 'stack'
config:
  default:
    name: 'Default pipeline'
    description: 'This is a pipeline description, necessary to let the user which pipeline to use.'
    pipeline:
      pipeline:
        path: 'default/pipeline/magento.yml'
      variables:
        destination: ($ project $)/default/pipeline/variables-($ environment $).yml
        path: 'default/pipeline/variables.sample.yml'

    # Configuration of terraform to setup the infrastructure
    terraform:
      magento:
        path: 'default/terraform/magento.tf.sample'
        destination: '($ project $)/default/terraform/magento/($ environment $)/magento.tf'
