first-usecase:
  pipeline:
    SimpleText:
    - widget: "simple_text"
      default: "test"
      type: "string"
      description: "key: simple_text_string"
      key: "simple_text_string"
      name: "SimpleText (String)"
    Number:
    - widget: "number"
      default: 12
      type: "integer"
      description: "key: number_integer"
      key: "number_integer"
      name: "Number (Integer)"
    AutoComplete:
    - widget: "auto_complete"
      type: "string"
      default: "test"
      values: ["un", "dos", "tres", "test"]
      description: "key: autocomplete_string"
      key: "autocomplete_string"
      name: "Autocomplete (String)"
    SliderRange:
    - widget: "slider_range"
      default: 15
      type: "integer"
      unit: "Ghz"
      values: [0, 60]
      description: "key: slider_range_integer"
      key: "slider_range_integer"
      name: "SliderRange (Integer)"
    SliderList:
    - widget: "slider_list"
      type: "string"
      default: "tres"
      values: ["un", "dos", "tres"]
      description: "key: slider_list_string"
      key: "slider_list_string"
      name: "Slider List (String)"
    - widget: "slider_list"
      type: "boolean"
      default: false
      values: [true, false]
      description: "key: slider_list_boolean"
      key: "slider_list_boolean"
      name: "Slider List (Boolean)"
    - widget: "slider_list"
      type: "integer"
      default: 4
      values: [2, 4, 6, 8, 10]
      description: "key: slider_list_integer"
      key: "slider_list_integer"
      name: "Slider List (Integer)"

    Textarea:
    - widget: "text_area"
      default: "extra info here"
      unit: "simple words"
      type: "string"
      description: "key: text_area_string"
      key: "text_area_string"
      name: "Textarea (String)"
    - widget: "text_area"
      default: 3
      type: "integer"
      description: "key: text_area_integer"
      key: "text_area_integer"
      name: "Textarea (Integer)"
    - widget: "text_area"
      default: true
      type: "boolean"
      description: "key: text_area_boolean"
      key: "text_area_boolean"
      name: "Textarea (Boolean)"
    - widget: "text_area"
      default: [1, 2, 3]
      type: "array"
      description: "key: text_area_array"
      key: "text_area_array"
      name: "Textarea (Array)"
    - widget: "text_area"
      default: { myvar: 'key' }
      type: "map"
      description: "key: text_area_map"
      key: "text_area_map"
      name: "Textarea (Map)"
    Dropdown:
    - widget: "dropdown"
      values: ["un", "dos", "tres"]
      default: "tres"
      type: "string"
      description: "key: dropdown_string"
      key: "dropdown_string"
      name: "Dropdown (String)"
    - widget: "dropdown"
      values: [1, 2, 3]
      default: 3
      type: "integer"
      description: "key: dropdown_integer"
      key: "dropdown_integer"
      name: "Dropdown (Integer)"
    - widget: "dropdown"
      values: [true, false]
      default: true
      type: "boolean"
      description: "key: dropdown_boolean"
      key: "dropdown_boolean"
      name: "Dropdown (Boolean)"
    - widget: "dropdown"
      values: [[1, 2, 3], [4, 5, 6], ["a", "b", "c"]]
      default: [1, 2, 3]
      type: "array"
      description: "key: dropdown_array"
      key: "dropdown_array"
      name: "Dropdown (Array)"
    - widget: "dropdown"
      values: [{ myvar: 'key' }, { myvar2: true }, { myvar3: 3 }]
      default: { myvar: 'key' }
      type: "map"
      description: "key: dropdown_map"
      key: "dropdown_map"
      name: "Dropdown (Map)"
    Radios:
    - widget: "radios"
      values: ["un", "dos", "tres"]
      default: "tres"
      type: "string"
      description: "key: radios_string"
      key: "radios_string"
      name: "Radios (String)"
    - widget: "radios"
      values: [1, 2, 3]
      default: 3
      type: "integer"
      description: "key: radios_integer"
      key: "radios_integer"
      name: "Radios (Integer)"
    - widget: "radios"
      values: [true, false]
      default: true
      type: "boolean"
      description: "key: radios_boolean"
      key: "radios_boolean"
      name: "Radios (Boolean)"
    - widget: "radios"
      values: [[1, 2, 3], [4, 5, 6], ["a", "b", "c"]]
      default: [1, 2, 3]
      type: "array"
      description: "key: radios_array"
      key: "radios_array"
      name: "Radios (Array)"
    - widget: "radios"
      values: [{ myvar: 'key' }, { myvar2: true }, { myvar3: 3 }]
      default: { myvar: 'key' }
      type: "map"
      description: "key: radios_map"
      key: "radios_map"
      name: "Radios (Map)"

    Credentials:
    - widget: "cy_cred"
      default: "aws_my_aws/secret_key"
      type: "string"
      description: "key: cred_string"
      key: "cred_string"
      name: "Credentials (String)"
    Stacks, ConfigRepository and Branch:
    - widget: "cy_scs"
      default: "git@github.com:dangzo/sc-test.git"
      type: "string"
      description: "key: scs_string"
      key: "scs_string"
      name: "Stacks (String)"
    - widget: "cy_crs"
      default: "git@github.com:dangzo/sc-test.git"
      type: "string"
      description: "key: crs_string"
      key: "crs_string"
      name: "Config Repository (String)"
    - widget: "cy_branch"
      default: "stacks-staging"
      type: "string"
      description: "key: branch_crs_string"
      key: "branch_crs_string"
      name: "Branch CR (String)"
      source: "crs_string"
    - widget: "cy_branch"
      default: "config-staging"
      type: "string"
      description: "key: branch_scs_string"
      key: "branch_scs_string"
      name: "Branch Stacks (String)"
      source: "scs_string"
second-usecase:
  ansible:
    group1:
    - widget: "text_area"
      default: "don't matter"
      type: "string"
      description: "Some stuff"
      key: "var"
      name: "var with imaginary friends"