first-usecase:
  pipeline:
    group1:
    - widget: "simple_text"
      default: "nobucket"
      type: "string"
      description: "Bucket used to store magento code"
      key: "magento_deploy_bucket_name"
      name: "Magento bucket"
    - widget: "text_area"
      default: "extra info here"
      unit: "simple words"
      type: "string"
      description: "Doesn't matter"
      key: "no-exist"
      name: "Extra info"
    - widget: "number"
      default: 12
      type: "integer"
      description: "Number of instances to be created"
      key: "instances_number"
      name: "Instances"
  terraform:
    group2:
    - widget: "dropdown"
      type: "string"
      default: "dw-502"
      values: ["ax-123", "cb-317", "dw-502"]
      description: "A list of network IDs (dropdown)"
      key: "module.magento.net_ids_dd"
      name: "Network IDs"
    - widget: "auto_complete"
      type: "string"
      default: "dw-502"
      values: ["ax-123", "cb-317", "dw-502"]
      description: "A list of network IDs (auto_complete)"
      key: "module.magento.net_ids_ac"
      name: "Network IDs"
    group3:
    - widget: "slider_list"
      type: "string"
      default: "dw-502"
      values: ["ax-123", "cb-317", "dw-502"]
      description: "A list of network IDs (slider_list)"
      key: "module.magento.net_ids_sl"
      name: "Network IDs"
    - widget: "radios"
      type: "string"
      default: "disabled"
      values: ["enabled", "disabled"]
      description: "VPC status"
      key: "module.magento.vpc_status"
      name: "VPC status"
    - widget: "slider_range"
      default: 15
      type: "integer"
      unit: "Ghz"
      values: [0, 60]
      description: "Fault tolerance"
      key: "module.magento.fault_tolerange"
      name: "Fault tolerance"
second-usecase:
  ansible:
    group4:
    - widget: "cy_cred"
      default: "aws_my_aws/secret_key"
      type: "string"
      description: "A credential to use"
      key: "db_cred"
      name: "DB credential"
    - widget: "cy_scs"
      default: "git@github.com:dangzo/sc-test.git"
      type: "string"
      description: "The stack to use"
      key: "scs_to_use"
      name: "Stack"
    - widget: "cy_crs"
      default: "git@github.com:dangzo/sc-test.git"
      type: "string"
      description: "The config repository to use"
      key: "crs_to_use"
      name: "Config repository"
    - widget: "cy_branch"
      default: "stacks-staging"
      type: "string"
      description: "The branch to use with the CR"
      key: "cr_branch"
      name: "CR branch"
      source: "crs_to_use"
    - widget: "cy_branch"
      default: "config-staging"
      type: "string"
      description: "The branch to use with the Stack"
      key: "stack_branch"
      name: "Stack branch"
      source: "scs_to_use"
imaginy-use-case:
  ansible:
    group1:
    - widget: "text_area"
      default: "don't matter"
      type: "string"
      description: "Some stuff"
      key: "var"
      name: "var with imaginary friends"