version: "2"
name: del-del
canonical: del-del
description: Deploys a Node.js web application on one instance using Terraform and Cloud-Init.
author: 'javier_tarulla'
image: 'https://github.com/cycloidio/bootstrap-stacks/blob/master/blank-sample/thumbnail.png'
status: 'private'
template: false
keywords:
  - terraform
  - cloud-init
  - user data
  - webapp
  - nodejs
  - nginx
  - provider:aws
technologies:
  - technology: terraform
    version: 1.5.7
  - technology: nodejs
  - technology: nginx
config:
  aws:
    name: 'AWS'
    description: 'Deploys a Node.js web application in a single AWS instance'
    cloud_provider: aws
    # Pipeline and variable configuration for the AWS CD pipeline use case
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/($ environment $)/variables.yml'
    # Configuration of terraform (leave .sample extension to prevent terraform executing the sample file)
    terraform:
      main:
        path: 'terraform/aws/main.tf'
        destination: '($ project $)/terraform/aws/($ environment $)/main.tf'
